// propkit-cli generator — produce standalone proptest test files
//
// Copyright 2026 Joseph O'Brien
// SPDX-License-Identifier: MIT OR Apache-2.0

use crate::analyzer::{Confidence, FileAnalysis, Property, TypeInfo};

pub fn generate_tests(analyses: &[FileAnalysis], min_confidence: Confidence) -> String {
    let mut out = String::new();
    out.push_str("// Generated by propkit — standalone property tests\n");
    out.push_str("// These tests depend only on proptest, not on propkit.\n\n");
    out.push_str("use proptest::prelude::*;\n\n");

    let mut has_tests = false;

    out.push_str("proptest! {\n");

    for analysis in analyses {
        for ty in &analysis.types {
            let filtered: Vec<&Property> = ty
                .properties
                .iter()
                .filter(|p| confidence_ge(p.confidence, min_confidence))
                .collect();
            if filtered.is_empty() {
                continue;
            }
            for prop in &filtered {
                if let Some(test) = generate_type_test(ty, prop) {
                    has_tests = true;
                    out.push_str(&test);
                    out.push('\n');
                }
            }
        }

        for func in &analysis.functions {
            let filtered: Vec<&Property> = func
                .properties
                .iter()
                .filter(|p| confidence_ge(p.confidence, min_confidence))
                .collect();
            for prop in &filtered {
                has_tests = true;
                out.push_str(&format!(
                    "    // TODO: {} — {}\n",
                    func.name, prop.description
                ));
                out.push_str(&format!(
                    "    // #[test]\n    // fn test_{}_{}() {{ /* ... */ }}\n\n",
                    func.name,
                    prop.description.replace(['/', ' ', ','], "_")
                ));
            }
        }
    }

    out.push_str("}\n");

    if !has_tests {
        return String::new();
    }

    out
}

fn confidence_ge(c: Confidence, min: Confidence) -> bool {
    confidence_rank(c) >= confidence_rank(min)
}

fn confidence_rank(c: Confidence) -> u8 {
    match c {
        Confidence::Low => 0,
        Confidence::Medium => 1,
        Confidence::High => 2,
    }
}

fn generate_type_test(ty: &TypeInfo, prop: &Property) -> Option<String> {
    let name = &ty.name;
    let snake = to_snake_case(name);

    match prop.description.as_str() {
        "hash/eq consistency" => Some(format!(
            r#"    #[test]
    fn {snake}_hash_eq_consistency(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // use std::hash::{{Hash, Hasher, DefaultHasher}};
        // let mut h1 = DefaultHasher::new();
        // let mut h2 = DefaultHasher::new();
        // let a = {name}::from(_x);
        // let b = a.clone();
        // a.hash(&mut h1);
        // b.hash(&mut h2);
        // prop_assert_eq!(h1.finish(), h2.finish());
    }}
"#
        )),
        "clone equality" => Some(format!(
            r#"    #[test]
    fn {snake}_clone_equality(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // let a = {name}::from(_x);
        // let b = a.clone();
        // prop_assert_eq!(a, b);
    }}
"#
        )),
        "serde roundtrip" => Some(format!(
            r#"    #[test]
    fn {snake}_serde_roundtrip(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // let original = {name}::from(_x);
        // let json = serde_json::to_string(&original).unwrap();
        // let decoded: {name} = serde_json::from_str(&json).unwrap();
        // prop_assert_eq!(original, decoded);
    }}
"#
        )),
        "parse/display roundtrip" => Some(format!(
            r#"    #[test]
    fn {snake}_parse_display_roundtrip(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // let original = {name}::from(_x);
        // let s = original.to_string();
        // let parsed: {name} = s.parse().unwrap();
        // prop_assert_eq!(original, parsed);
    }}
"#
        )),
        "default doesn't panic" => Some(format!(
            r#"    #[test]
    fn {snake}_default_does_not_panic(_x in any::<u8>()) {{
        // let _ = {name}::default();
    }}
"#
        )),
        "transitivity, antisymmetry, totality" => Some(format!(
            r#"    #[test]
    fn {snake}_ord_transitivity(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // let a = {name}::from(_x);
        // let b = {name}::from(_x);
        // let c = {name}::from(_x);
        // if a <= b && b <= c {{ prop_assert!(a <= c); }}
    }}
"#
        )),
        "reflexivity, antisymmetry" => Some(format!(
            r#"    #[test]
    fn {snake}_partial_ord_reflexivity(
        // TODO: replace with any::<{name}>() or a prop_compose! strategy
        _x in any::<u8>()
    ) {{
        // let a = {name}::from(_x);
        // prop_assert!(a <= a);
    }}
"#
        )),
        _ => None,
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap());
        } else {
            result.push(c);
        }
    }
    result
}
