// propkit-cli smolvm scaffold generator
//
// Copyright 2026 Joseph O'Brien
// SPDX-License-Identifier: MIT OR Apache-2.0

pub fn generate(crate_name: &str) -> String {
    format!(
        r#"// Generated by propkit — smolvm integration test helpers for {crate_name}
// These helpers have no dependency on propkit at runtime.
//
// Usage: place this file in tests/smolvm_helpers.rs and use as a module:
//   mod smolvm_helpers;
//   use smolvm_helpers::{{SmolvmMachine, free_port, smolvm_available}};

use std::net::TcpListener;
use std::process::{{Command, Stdio}};
use std::time::{{Duration, Instant}};

/// Check whether `smolvm` is available on PATH.
pub fn smolvm_available() -> bool {{
    Command::new("smolvm")
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}}

/// Skip the calling test if smolvm is not available.
#[macro_export]
macro_rules! smolvm_or_skip {{
    () => {{
        if !$crate::smolvm_helpers::smolvm_available() {{
            eprintln!("SKIP: smolvm not available");
            return;
        }}
    }};
}}

/// Find a free TCP port by binding to port 0.
pub fn free_port() -> u16 {{
    let listener = TcpListener::bind("127.0.0.1:0")
        .expect("failed to bind ephemeral port");
    listener.local_addr().unwrap().port()
}}

/// Block until a TCP connection to `addr` succeeds or `timeout` elapses.
pub fn wait_for_tcp(addr: &str, timeout: Duration) -> bool {{
    let start = Instant::now();
    let interval = Duration::from_millis(100);
    while start.elapsed() < timeout {{
        if std::net::TcpStream::connect(addr).is_ok() {{
            return true;
        }}
        std::thread::sleep(interval);
    }}
    false
}}

/// RAII guard for a smolvm machine. Stops and removes the machine on drop.
pub struct SmolvmMachine {{
    name: String,
    stopped: bool,
}}

impl SmolvmMachine {{
    /// Create and start a new smolvm machine from the given image.
    pub fn start(image: &str, name: &str, ports: &[(u16, u16)]) -> Self {{
        let port_args: Vec<String> = ports
            .iter()
            .map(|(host, guest)| format!("-p {{}}:{{}}", host, guest))
            .collect();
        let status = Command::new("smolvm")
            .args(["create", "--name", name, "--image", image])
            .args(&port_args)
            .status()
            .expect("failed to create smolvm machine");
        assert!(status.success(), "smolvm create failed");

        let status = Command::new("smolvm")
            .args(["start", name])
            .status()
            .expect("failed to start smolvm machine");
        assert!(status.success(), "smolvm start failed");

        Self {{
            name: name.to_string(),
            stopped: false,
        }}
    }}

    /// Stop the machine without removing it.
    pub fn stop(&mut self) {{
        if !self.stopped {{
            let _ = Command::new("smolvm")
                .args(["stop", &self.name])
                .status();
            self.stopped = true;
        }}
    }}

    /// The machine name.
    pub fn name(&self) -> &str {{
        &self.name
    }}
}}

impl Drop for SmolvmMachine {{
    fn drop(&mut self) {{
        self.stop();
        let _ = Command::new("smolvm")
            .args(["rm", "--force", &self.name])
            .status();
    }}
}}

/// Start a PostgreSQL instance via smolvm. Returns (machine, connection_url).
pub fn start_postgres(
    port: u16,
    password: &str,
    timeout: Duration,
) -> (SmolvmMachine, String) {{
    let name = format!("propkit-pg-{{}}", port);
    let machine = SmolvmMachine::start("postgres:16", &name, &[(port, 5432)]);
    let addr = format!("127.0.0.1:{{}}", port);
    assert!(
        wait_for_tcp(&addr, timeout),
        "PostgreSQL did not become ready within {{:?}}",
        timeout
    );
    let url = format!(
        "postgres://postgres:{{}}@127.0.0.1:{{}}/postgres",
        password, port
    );
    (machine, url)
}}

/// Start a Redis instance via smolvm. Returns (machine, address).
pub fn start_redis(port: u16, timeout: Duration) -> (SmolvmMachine, String) {{
    let name = format!("propkit-redis-{{}}", port);
    let machine = SmolvmMachine::start("redis:7", &name, &[(port, 6379)]);
    let addr = format!("127.0.0.1:{{}}", port);
    assert!(
        wait_for_tcp(&addr, timeout),
        "Redis did not become ready within {{:?}}",
        timeout
    );
    (machine, addr)
}}

/// Start a Redis instance with password authentication.
pub fn start_redis_with_auth(
    port: u16,
    password: &str,
    timeout: Duration,
) -> (SmolvmMachine, String) {{
    let name = format!("propkit-redis-auth-{{}}", port);
    // Redis AUTH is set via the --requirepass flag in the CMD.
    let machine = SmolvmMachine::start(
        &format!("redis:7 --requirepass {{}}", password),
        &name,
        &[(port, 6379)],
    );
    let addr = format!("127.0.0.1:{{}}", port);
    assert!(
        wait_for_tcp(&addr, timeout),
        "Redis (auth) did not become ready within {{:?}}",
        timeout
    );
    (machine, addr)
}}
"#,
        crate_name = crate_name,
    )
}
