// propkit-cli testlinux scaffold generator
//
// Copyright 2026 Joseph O'Brien
// SPDX-License-Identifier: MIT OR Apache-2.0

pub fn generate(crate_name: &str) -> String {
    format!(
        r##"// Generated by propkit — TestLinux VM runner for {crate_name}
// These helpers have no dependency on propkit at runtime.
//
// Usage: place this file in tests/testlinux.rs and use as a module:
//   mod testlinux;
//   use testlinux::{{TestLinux, MuslCompiler, CpioInitramfs, QemuHvf}};

use std::path::{{Path, PathBuf}};
use std::process::{{Command, Stdio}};
use std::time::Duration;

/// Result of running tests inside a VM.
#[derive(Debug)]
pub struct TestResult {{
    pub passed: usize,
    pub failed: usize,
    pub output: String,
}}

/// Cross-compile a test binary for a target triple.
pub trait Compiler {{
    fn compile(&self, crate_dir: &Path, out_dir: &Path) -> Result<PathBuf, String>;
}}

/// Build an initramfs image containing the test binary.
pub trait InitramfsBuilder {{
    fn build(&self, test_binary: &Path, out_dir: &Path) -> Result<PathBuf, String>;
}}

/// Boot a kernel + initramfs and parse test output.
pub trait VmRunner {{
    fn run(&self, kernel: &Path, initramfs: &Path) -> Result<TestResult, String>;
}}

/// Cross-compiler using cargo-zigbuild for musl targets.
pub struct MuslCompiler {{
    pub target: String,
    pub profile: String,
}}

impl Default for MuslCompiler {{
    fn default() -> Self {{
        Self {{
            target: "x86_64-unknown-linux-musl".to_string(),
            profile: "dev".to_string(),
        }}
    }}
}}

impl Compiler for MuslCompiler {{
    fn compile(&self, crate_dir: &Path, out_dir: &Path) -> Result<PathBuf, String> {{
        let status = Command::new("cargo")
            .args([
                "zigbuild",
                "--target", &self.target,
                "--profile", &self.profile,
                "--tests",
                "--target-dir",
            ])
            .arg(out_dir)
            .current_dir(crate_dir)
            .status()
            .map_err(|e| format!("failed to run cargo zigbuild: {{e}}"))?;
        if !status.success() {{
            return Err("cargo zigbuild failed".to_string());
        }}
        // Find the test binary in the target dir
        let bin_dir = out_dir
            .join(&self.target)
            .join(if self.profile == "dev" {{ "debug" }} else {{ &self.profile }})
            .join("deps");
        let entry = std::fs::read_dir(&bin_dir)
            .map_err(|e| format!("cannot read {{bin_dir:?}}: {{e}}"))?
            .filter_map(|e| e.ok())
            .find(|e| {{
                let p = e.path();
                p.is_file()
                    && !p.extension().is_some_and(|ext| ext == "d" || ext == "rmeta")
            }})
            .ok_or_else(|| format!("no test binary found in {{bin_dir:?}}"))?;
        Ok(entry.path())
    }}
}}

/// Build a cpio initramfs with the test binary as /init.
pub struct CpioInitramfs;

impl InitramfsBuilder for CpioInitramfs {{
    fn build(&self, test_binary: &Path, out_dir: &Path) -> Result<PathBuf, String> {{
        let root = out_dir.join("initramfs_root");
        std::fs::create_dir_all(&root)
            .map_err(|e| format!("mkdir initramfs_root: {{e}}"))?;

        // Copy test binary as /test_bin
        let dest = root.join("test_bin");
        std::fs::copy(test_binary, &dest)
            .map_err(|e| format!("copy test binary: {{e}}"))?;

        // Write /init script
        let init_script = build_run_tests_sh();
        let init_path = root.join("init");
        std::fs::write(&init_path, init_script)
            .map_err(|e| format!("write init: {{e}}"))?;

        #[cfg(unix)]
        {{
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&init_path, std::fs::Permissions::from_mode(0o755))
                .map_err(|e| format!("chmod init: {{e}}"))?;
            std::fs::set_permissions(&dest, std::fs::Permissions::from_mode(0o755))
                .map_err(|e| format!("chmod test_bin: {{e}}"))?;
        }}

        // Build cpio archive
        let initramfs = out_dir.join("initramfs.cpio");
        let find = Command::new("find")
            .arg(".")
            .current_dir(&root)
            .stdout(Stdio::piped())
            .spawn()
            .map_err(|e| format!("find: {{e}}"))?;

        let cpio = Command::new("cpio")
            .args(["-o", "--format=newc"])
            .current_dir(&root)
            .stdin(find.stdout.unwrap())
            .stdout(std::fs::File::create(&initramfs)
                .map_err(|e| format!("create initramfs: {{e}}"))?)
            .status()
            .map_err(|e| format!("cpio: {{e}}"))?;

        if !cpio.success() {{
            return Err("cpio failed".to_string());
        }}
        Ok(initramfs)
    }}
}}

/// QEMU runner using HVF acceleration (macOS) with serial output parsing.
pub struct QemuHvf {{
    pub kernel_path: PathBuf,
    pub timeout: Duration,
    pub memory_mb: u32,
}}

impl Default for QemuHvf {{
    fn default() -> Self {{
        Self {{
            kernel_path: PathBuf::from("/usr/local/share/linux/vmlinuz"),
            timeout: Duration::from_secs(60),
            memory_mb: 256,
        }}
    }}
}}

impl VmRunner for QemuHvf {{
    fn run(&self, kernel: &Path, initramfs: &Path) -> Result<TestResult, String> {{
        let output = Command::new("qemu-system-x86_64")
            .args([
                "-accel", "hvf",
                "-m", &format!("{{}}", self.memory_mb),
                "-kernel",
            ])
            .arg(kernel)
            .arg("-initrd")
            .arg(initramfs)
            .args([
                "-append", "console=ttyS0 panic=-1",
                "-nographic",
                "-no-reboot",
                "-serial", "stdio",
            ])
            .output()
            .map_err(|e| format!("qemu: {{e}}"))?;

        let stdout = String::from_utf8_lossy(&output.stdout).to_string();

        // Parse test output: look for "test result: ok. N passed; M failed"
        let (passed, failed) = parse_test_output(&stdout);

        Ok(TestResult {{
            passed,
            failed,
            output: stdout,
        }})
    }}
}}

/// Parse Rust test runner output for pass/fail counts.
fn parse_test_output(output: &str) -> (usize, usize) {{
    for line in output.lines().rev() {{
        if line.contains("test result:") {{
            let passed = extract_count(line, "passed");
            let failed = extract_count(line, "failed");
            return (passed, failed);
        }}
    }}
    (0, 0)
}}

fn extract_count(line: &str, label: &str) -> usize {{
    line.split(';')
        .chain(line.split('.'))
        .find(|seg| seg.contains(label))
        .and_then(|seg| {{
            seg.split_whitespace()
                .find_map(|w| w.parse::<usize>().ok())
        }})
        .unwrap_or(0)
}}

/// Generate the /init shell script that runs tests and powers off.
pub fn build_run_tests_sh() -> String {{
    r#"#!/bin/sh
set -e
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev

echo "=== TestLinux: running tests ==="
/test_bin --test-threads=1 2>&1
EXIT=$?
echo "=== TestLinux: exit code $EXIT ==="
poweroff -f
"#.to_string()
}}

/// TestLinux orchestrator — wires compile, initramfs, and VM boot.
pub struct TestLinux<C, I, V> {{
    pub compiler: C,
    pub initramfs_builder: I,
    pub vm_runner: V,
}}

impl<C: Compiler, I: InitramfsBuilder, V: VmRunner> TestLinux<C, I, V> {{
    pub fn new(compiler: C, initramfs_builder: I, vm_runner: V) -> Self {{
        Self {{
            compiler,
            initramfs_builder,
            vm_runner,
        }}
    }}

    /// Compile, build initramfs, boot VM, and return test results.
    pub fn run(&self, crate_dir: &Path, kernel: &Path) -> Result<TestResult, String> {{
        let out_dir = std::env::temp_dir().join("testlinux");
        std::fs::create_dir_all(&out_dir)
            .map_err(|e| format!("mkdir out_dir: {{e}}"))?;

        let test_binary = self.compiler.compile(crate_dir, &out_dir)?;
        let initramfs = self.initramfs_builder.build(&test_binary, &out_dir)?;
        self.vm_runner.run(kernel, &initramfs)
    }}
}}
"##,
        crate_name = crate_name,
    )
}
